FROM node:20-bullseye

RUN apt-get update && apt-get install -y openjdk-17-jre ffmpeg && apt-get clean

ENV RESULTS_ACCESS=processor/target

ENV VIDEOS_ACCESS=processor/src/main/resources/videos

WORKDIR /server

EXPOSE 3000

COPY . .

RUN npm i

RUN npm install ffmpeg-static

CMD ["npm", "start"]
